export type ScaledPropertyName = keyof typeof scaledProperties;
export declare const scaledProperties: {
    contentLength: (length: number) => string;
    lexicalComplexity: (level: number) => string;
    lexicalDiversity: (level: number) => string;
    lexicalRichness: (level: number) => string;
    lexicalDensity: (level: number) => string;
    register: (level: number) => string;
    syntacticComplexity: (level: number) => string;
    creativity: (level: number) => string;
    descriptiveness: (level: number) => string;
    personality: (level: number) => string;
    verbosity: (level: number) => string;
    pacing: (level: number) => string;
    emotionalIntensity: (level: number) => string;
    dialogueFocus: (level: number) => string;
    complexity: (level: number) => string;
    poetic: (level: number) => string;
    ornateness: (level: number) => string;
    floweriness: (level: number) => string;
};
