export declare enum Tone {
    Lighthearted = "Lighthearted",
    Meditative = "Meditative",
    Humorous = "Humorous",
    Serious = "Serious",
    Dark = "Dark",
    Romantic = "Romantic",
    Erotic = "Erotic",
    Melancholy = "Melancholy",
    Suspenseful = "Suspenseful",
    Nostalgic = "Nostalgic",
    Sentimental = "Sentimental",
    Sarcastic = "Sarcastic",
    Satirical = "Satirical",
    Mystical = "Mystical",
    Surreal = "Surreal",
    Absurd = "Absurd",
    Dramatic = "Dramatic",
    Melodramatic = "Melodramatic",
    Tragic = "Tragic",
    Comedic = "Comedic",
    Gothic = "Gothic"
}
