"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Genre = void 0;
var Genre;
(function (Genre) {
    Genre["Action"] = "Action";
    Genre["Adventure"] = "Adventure";
    Genre["Autobiography"] = "Autobiography";
    Genre["Biography"] = "Biography";
    Genre["Business"] = "Business";
    Genre["Childrens"] = "Children's";
    Genre["Comedy"] = "Comedy";
    Genre["Crime"] = "Crime";
    Genre["Cyberpunk"] = "Cyberpunk";
    Genre["Drama"] = "Drama";
    Genre["Dystopian"] = "Dystopian";
    Genre["Educational"] = "Educational";
    Genre["Epic"] = "Epic";
    Genre["Fantasy"] = "Fantasy";
    Genre["GraphicNovel"] = "Graphic Novel";
    Genre["Health"] = "Health";
    Genre["Historical"] = "Historical";
    Genre["Horror"] = "Horror";
    Genre["Memoir"] = "Memoir";
    Genre["Mystery"] = "Mystery";
    Genre["Noir"] = "Noir";
    Genre["NonFiction"] = "Non-Fiction";
    Genre["Paranormal"] = "Paranormal";
    Genre["Philosophy"] = "Philosophy";
    Genre["Poetry"] = "Poetry";
    Genre["Political"] = "Political";
    Genre["PostApocalyptic"] = "Post-Apocalyptic";
    Genre["Religion"] = "Religion";
    Genre["Romance"] = "Romance";
    Genre["Saga"] = "Saga";
    Genre["Satire"] = "Satire";
    Genre["Science"] = "Science";
    Genre["ScienceFiction"] = "Science Fiction";
    Genre["SelfHelp"] = "Self-Help";
    Genre["SouthernGothic"] = "Southern Gothic";
    Genre["SpaceOpera"] = "Space Opera";
    Genre["Steampunk"] = "Steampunk";
    Genre["Technology"] = "Technology";
    Genre["Thriller"] = "Thriller";
    Genre["Travel"] = "Travel";
    Genre["TrueCrime"] = "True Crime";
    Genre["UrbanFantasy"] = "Urban Fantasy";
    Genre["Western"] = "Western";
    Genre["YoungAdult"] = "Young Adult";
})(Genre || (exports.Genre = Genre = {}));
