"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Style = void 0;
var Style;
(function (Style) {
    Style["Expository"] = "Expository";
    Style["Descriptive"] = "Descriptive";
    Style["Narrative"] = "Narrative";
    Style["Persuasive"] = "Persuasive";
    Style["Poetic"] = "Poetic";
    Style["Ornate"] = "Ornate";
    Style["Flowery"] = "Flowery";
    Style["Plain"] = "Plain";
    Style["Formal"] = "Formal";
    Style["Informal"] = "Informal";
    Style["Casual"] = "Casual";
    Style["Conversational"] = "Conversational";
    Style["Technical"] = "Technical";
    Style["Scientific"] = "Scientific";
    Style["Journalistic"] = "Journalistic";
    Style["Academic"] = "Academic";
    Style["Business"] = "Business";
    Style["Legal"] = "Legal";
    Style["Medical"] = "Medical";
    Style["StreamOfConsciousness"] = "Stream of Consciousness";
    Style["Experimental"] = "Experimental";
})(Style || (exports.Style = Style = {}));
