"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Theme = void 0;
var Theme;
(function (Theme) {
    Theme["Love"] = "Love";
    Theme["Power"] = "Power";
    Theme["Survival"] = "Survival";
    Theme["Corruption"] = "Corruption";
    Theme["Freedom"] = "Freedom";
    Theme["Justice"] = "Justice";
    Theme["Prejudice"] = "Prejudice";
    Theme["Individuality"] = "Individuality";
    Theme["Sacrifice"] = "Sacrifice";
    Theme["Identity"] = "Identity";
    Theme["Redemption"] = "Redemption";
    Theme["Courage"] = "Courage";
    Theme["Betrayal"] = "Betrayal";
    Theme["Friendship"] = "Friendship";
    Theme["War"] = "War";
    Theme["Peace"] = "Peace";
    Theme["Technology"] = "Technology";
    Theme["Nature"] = "Nature";
    Theme["Exploration"] = "Exploration";
    Theme["Innovation"] = "Innovation";
    Theme["Tradition"] = "Tradition";
    Theme["Change"] = "Change";
    Theme["Fate"] = "Fate";
    Theme["Morality"] = "Morality";
    Theme["Ambition"] = "Ambition";
    Theme["Revenge"] = "Revenge";
    Theme["Greed"] = "Greed";
    Theme["Fear"] = "Fear";
    Theme["Happiness"] = "Happiness";
    Theme["Suffering"] = "Suffering";
    Theme["Mystery"] = "Mystery";
    Theme["Fantasy"] = "Fantasy";
    Theme["History"] = "History";
    Theme["Mythology"] = "Mythology";
})(Theme || (exports.Theme = Theme = {}));
