"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Tone = void 0;
var Tone;
(function (Tone) {
    Tone["Lighthearted"] = "Lighthearted";
    Tone["Meditative"] = "Meditative";
    Tone["Humorous"] = "Humorous";
    Tone["Serious"] = "Serious";
    Tone["Dark"] = "Dark";
    Tone["Romantic"] = "Romantic";
    Tone["Erotic"] = "Erotic";
    Tone["Melancholy"] = "Melancholy";
    Tone["Suspenseful"] = "Suspenseful";
    Tone["Nostalgic"] = "Nostalgic";
    Tone["Sentimental"] = "Sentimental";
    Tone["Sarcastic"] = "Sarcastic";
    Tone["Satirical"] = "Satirical";
    Tone["Mystical"] = "Mystical";
    Tone["Surreal"] = "Surreal";
    Tone["Absurd"] = "Absurd";
    Tone["Dramatic"] = "Dramatic";
    Tone["Melodramatic"] = "Melodramatic";
    Tone["Tragic"] = "Tragic";
    Tone["Comedic"] = "Comedic";
    Tone["Gothic"] = "Gothic";
})(Tone || (exports.Tone = Tone = {}));
